FROM ubuntu:20.04

ARG DEBIAN_FRONTEND=noninteractive
ENV TERM xterm-256color
ENV TZ $(cat /etc/timezone)

RUN ln -snf /usr/share/zoneinfo/UTC /etc/localtime && echo UTC > /etc/timezone
RUN apt-get update && \
        apt-get upgrade -y && \
        apt-get -y install sudo \
        nano vim 

RUN useradd -m emulate && echo "emulate:emulate" | chpasswd && adduser emulate sudo
RUN echo "emulate ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
USER emulate
WORKDIR /home/emulate/

RUN sudo apt-get update && \
        sudo apt-get install -y git python3 python3-dev python3-pip python3-pexpect zip unzip rar unrar busybox-static fakeroot kpartx snmp uml-utilities util-linux vlan qemu-system-arm qemu-system-mips qemu-system-x86 qemu-utils lsb-core wget curl tar 

# Install Binwalk
RUN git clone --depth=1 https://github.com/devttys0/binwalk.git
RUN cd binwalk && sed -i 's;\$SUDO ./build.sh;wget https://github.com/devttys0/sasquatch/pull/47.patch \&\& patch -p1 < 47.patch \&\& \$SUDO ./build.sh;' deps.sh
RUN cd binwalk && sed -i '/REQUIRED_UTILS="wget tar python"/c\REQUIRED_UTILS="wget tar python3"' deps.sh
RUN cd binwalk && sudo ./deps.sh --yes
RUN cd binwalk && sudo python3 ./setup.py install
RUN sudo -H pip3 install git+https://github.com/ahupp/python-magic
RUN sudo -H pip3 install git+https://github.com/sviehb/jefferson

# Install firmadyne
RUN git clone --recursive https://github.com/firmadyne/firmadyne.git && \
    cd firmadyne && \
    ./download.sh && \
    firmadyne_dir=$(realpath .) && \
    sed -i "/FIRMWARE_DIR=/c\FIRMWARE_DIR=$firmadyne_dir" firmadyne.config && \
    sed -i 's/psql/#psql/' ./scripts/getArch.sh && \
    sudo touch /home/emulate/firmadyne/images/0.tar.gz && \
    cd ..

# Copy the emulate directory into the container
COPY emulate.sh /home/emulate/emulate.sh
RUN sudo chmod +x emulate.sh

#fix to /usr/bin/env python not found
RUN sudo ln -s /usr/bin/python3 /usr/bin/python

# Set the entrypoint
CMD /bin/bash
#ENTRYPOINT ["/home/emulate/emulate/emulate.sh"]
